In [2]:
!pip install -U fortran-magic
%reload_ext fortranmagic

!pip install --upgrade pandas-datareader

import pandas_datareader as pdr
import datetime

import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller
import matplotlib.pylab as plt
from matplotlib.pylab import rcParams

!pip install --upgrade quandl
!pip install yfinance
import yfinance as yf




%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

/usr/local/lib/python3.7/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


The fortranmagic extension is already loaded. To reload it, use:
  %reload_ext fortranmagic


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [285]:
assert ran_the_first_cell, "Oh noes!"

In [286]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

#My example 1

In [287]:
h = [598, 'caballo', 2.97865, 4.245, 1238, "vaca"]
h

[598, 'caballo', 2.97865, 4.245, 1238, 'vaca']

In [288]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


#My example 2

In [289]:
primero = h[0]
segundo = h[1]
print("primero:", primero)
print("segundo:", segundo)


primero: 598
segundo: caballo


In [290]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


#My example 3



In [291]:
ultimo = h[-1]
penultimo = h[-2]
print("ultimo:", ultimo)
print("penultimo:", penultimo)

ultimo: vaca
penultimo: 1238


In [292]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

#My example 4

In [293]:
sublista = h[0:2]
sublista


[598, 'caballo']

In [294]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

#My example 5

In [295]:
primero_tercero = h[:3]
primero_tercero


[598, 'caballo', 2.97865]

In [296]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

#My example 6


In [297]:
despues_tres = h[3:]
despues_tres

[4.245, 1238, 'vaca']

In [298]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

#My example 7

In [299]:
w = ['z', 'y', 'w', 'v', 'u', 'r', 's','t']
w[1:8:2]


['y', 'v', 'r', 't']

In [300]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

#My example 8


In [301]:
w[::-1]


['t', 's', 'r', 'u', 'v', 'w', 'y', 'z']

In [302]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


#My example 9


In [303]:
t = [9, 8, 7, 6, 5]
print("Antes:", t)
t.append('caballo')
print("despues:", t)

Antes: [9, 8, 7, 6, 5]
despues: [9, 8, 7, 6, 5, 'caballo']


In [304]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

#My example 10

In [305]:
t = [2, 4, 6, 8, 10]
[y * 2 for y in t]

[4, 8, 12, 16, 20]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [306]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

#My example 11


In [307]:
actores = {'leonardo': 'bale', 'tom': 'toby', 'roca': 'brad'}
actores

{'leonardo': 'bale', 'roca': 'brad', 'tom': 'toby'}

In [308]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'Bertrand': 'Russell',
 'David': 'Hume',
 'Immanuel': 'Kant',
 'Ludwig': 'Wittgenstein'}

#My example 12


In [309]:
actores['tom'] = 'cruise'
actores


{'leonardo': 'bale', 'roca': 'brad', 'tom': 'cruise'}

In [310]:
del philosophers['David']
philosophers

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

#My example 13


In [311]:
del actores['leonardo']
actores

{'roca': 'brad', 'tom': 'cruise'}

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [312]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

#My example 14


In [313]:
f = [[1, 1, 2],
     [3, 5, 8],
     [13, 21, 34],
     [55, 89, 100]]

p = [[3, 5, 7, 9],
     [11, 13, 15, 17]]

In [314]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

#My example 15


In [315]:
def matmul(F, P):
    """Multiply matrix A by matrix B."""
    rows_out = len(F)
    cols_out = len(P[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(T)):
                out[i][j] += F[i][k] * P[k][j]
    return out



<center><img src="images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [316]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.6236910886116375, 0.35178060435137604, 0.7374080197144912],
 [0.9834282862713456, 0.20939274376191508, 0.6935679849718572]]

#My example 16


In [317]:
import random
def random_matrix(a, b ):
    out = []
    for row in range(a):
        out.append([random.random() for _ in range(b)])
    return out

randm = random_matrix(4, 3)
randm

[[0.817997506223602, 0.8882909185227784, 0.1370860746996263],
 [0.7078543991212891, 0.9732775859893523, 0.31485013091893654],
 [0.8765663412564632, 0.8585683005529764, 0.9324901509782503],
 [0.825185230915928, 0.03250182070905849, 0.8744376975088868]]

In [318]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

#My example 17


In [319]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [320]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

#My example 18


In [321]:
list_dato = [float(h) for h in range(50000)]
array_dato = np.array(list_dato)

In [322]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 13 ms, sys: 0 ns, total: 13 ms
Wall time: 13.1 ms


333328333350000.0

#My example 19


In [323]:
%%time
python_dot_product(list_dato, list_dato)


CPU times: user 6.18 ms, sys: 0 ns, total: 6.18 ms
Wall time: 7.24 ms


41665416675000.0

<center><img src="images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [324]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

#My example 20


In [325]:
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([2, 4, 6, 8], [1, 3 + 5j, 7.0, 'nueve'])

[2, (12+20j), 42.0, 'nuevenuevenuevenuevenuevenuevenuevenueve']

## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [326]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

#My example 21


In [327]:
dato = np.array([6, 1, 9, 7])
dato


array([6, 1, 9, 7])

In [328]:
data + data

array([2, 4, 6, 8])

#My example 22


In [329]:
dato + dato

array([12,  2, 18, 14])

In [330]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 465 µs, sys: 73 µs, total: 538 µs
Wall time: 550 µs


333328333350000.0

#My example 23


In [331]:
%%time
(array_dato * array_dato).sum()

CPU times: user 258 µs, sys: 40 µs, total: 298 µs
Wall time: 309 µs


41665416675000.0

In [332]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 2.13 ms, sys: 335 µs, total: 2.47 ms
Wall time: 3.91 ms


333328333350000.0

#My example 24


In [333]:
array_dato.dot(array_dato)


41665416675000.0

In [334]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

#My example 25


In [335]:
d_por_d = dato.reshape(2, 2)
d_por_d

array([[6, 1],
       [9, 7]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [336]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


#My example 26


In [337]:
arr = np.array([78, 619, 715, 897, 289, 967], dtype='int16').reshape(3, 2)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[ 78 619]
 [715 897]
 [289 967]]
DType: int16
Shape: (3, 2)
Strides: (4, 2)
Data: b'N\x00k\x02\xcb\x02\x81\x03!\x01\xc7\x03'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [338]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#My example 27


In [339]:
dato = np.arange(49).reshape(7, 7)
dato

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [340]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

#My example 28


In [341]:
dato*dato

array([[   0,    1,    4,    9,   16,   25,   36],
       [  49,   64,   81,  100,  121,  144,  169],
       [ 196,  225,  256,  289,  324,  361,  400],
       [ 441,  484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089, 1156],
       [1225, 1296, 1369, 1444, 1521, 1600, 1681],
       [1764, 1849, 1936, 2025, 2116, 2209, 2304]])

In [342]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

#My example 29


In [343]:
np.sqrt(dato)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
        3.46410162, 3.60555128],
       [3.74165739, 3.87298335, 4.        , 4.12310563, 4.24264069,
        4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951, 5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265, 5.83095189],
       [5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
        6.32455532, 6.40312424],
       [6.4807407 , 6.55743852, 6.63324958, 6.70820393, 6.78232998,
        6.8556546 , 6.92820323]])

In [344]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

#My example 30


In [345]:
(dato % 8) == 0

array([[ True, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False],
       [False, False,  True, False, False, False, False],
       [False, False, False,  True, False, False, False],
       [False, False, False, False,  True, False, False],
       [False, False, False, False, False,  True, False],
       [False, False, False, False, False, False,  True]])

In [346]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

#My example 31


In [347]:
((dato % 5) == 0) & ((dato % 3) == 0)

array([[ True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False]])

In [348]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

#My example 32


In [349]:
dato @ dato.T


array([[   91,   238,   385,   532,   679,   826,   973],
       [  238,   728,  1218,  1708,  2198,  2688,  3178],
       [  385,  1218,  2051,  2884,  3717,  4550,  5383],
       [  532,  1708,  2884,  4060,  5236,  6412,  7588],
       [  679,  2198,  3717,  5236,  6755,  8274,  9793],
       [  826,  2688,  4550,  6412,  8274, 10136, 11998],
       [  973,  3178,  5383,  7588,  9793, 11998, 14203]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [350]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

#My example 33


In [351]:
senos = np.sin(np.linspace(1, 8.59, 54))
cosenos = np.cos(np.linspace(85, 7.15 , 12))
senos

array([ 0.84147098,  0.90996827,  0.95983544,  0.99005153,  0.99999793,
        0.989471  ,  0.95868625,  0.90827395,  0.83926623,  0.75307589,
        0.65146754,  0.53652146,  0.41059097,  0.27625429,  0.13626176,
       -0.00652051, -0.14916928, -0.28876406, -0.42244686, -0.54748074,
       -0.66130585, -0.76159179, -0.84628538, -0.91365265, -0.96231437,
       -0.99127426, -0.99993942, -0.98813245, -0.95609507, -0.90448319,
       -0.83435349, -0.74714176, -0.64463351, -0.52892744, -0.40239244,
       -0.26761911, -0.12736671,  0.01549332,  0.15803614,  0.29734344,
        0.4305631 ,  0.55496769,  0.66801022,  0.76737632,  0.85103163,
        0.91726346,  0.96471581,  0.99241717,  0.99980039,  0.98671433,
        0.9534269 ,  0.90061959,  0.82937357,  0.74114747])

In [352]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

#My example 34


In [353]:
senos[0]

0.8414709848078965

In [354]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

#My example 35


In [355]:
senos[:3]

array([0.84147098, 0.90996827, 0.95983544])

In [356]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

#My example 36


In [357]:
senos[5:]

array([ 0.989471  ,  0.95868625,  0.90827395,  0.83926623,  0.75307589,
        0.65146754,  0.53652146,  0.41059097,  0.27625429,  0.13626176,
       -0.00652051, -0.14916928, -0.28876406, -0.42244686, -0.54748074,
       -0.66130585, -0.76159179, -0.84628538, -0.91365265, -0.96231437,
       -0.99127426, -0.99993942, -0.98813245, -0.95609507, -0.90448319,
       -0.83435349, -0.74714176, -0.64463351, -0.52892744, -0.40239244,
       -0.26761911, -0.12736671,  0.01549332,  0.15803614,  0.29734344,
        0.4305631 ,  0.55496769,  0.66801022,  0.76737632,  0.85103163,
        0.91726346,  0.96471581,  0.99241717,  0.99980039,  0.98671433,
        0.9534269 ,  0.90061959,  0.82937357,  0.74114747])

In [358]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

#My example 37


In [359]:
senos[::2]

array([ 0.84147098,  0.95983544,  0.99999793,  0.95868625,  0.83926623,
        0.65146754,  0.41059097,  0.13626176, -0.14916928, -0.42244686,
       -0.66130585, -0.84628538, -0.96231437, -0.99993942, -0.95609507,
       -0.83435349, -0.64463351, -0.40239244, -0.12736671,  0.15803614,
        0.4305631 ,  0.66801022,  0.85103163,  0.96471581,  0.99980039,
        0.9534269 ,  0.82937357])

In [360]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


#My example 38


In [361]:
print("sines:\n", senos)
print("sines > 0.5:\n", senos > 0.5)
print("sines[sines > 0.5]:\n", senos[senos > 0.5])


sines:
 [ 0.84147098  0.90996827  0.95983544  0.99005153  0.99999793  0.989471
  0.95868625  0.90827395  0.83926623  0.75307589  0.65146754  0.53652146
  0.41059097  0.27625429  0.13626176 -0.00652051 -0.14916928 -0.28876406
 -0.42244686 -0.54748074 -0.66130585 -0.76159179 -0.84628538 -0.91365265
 -0.96231437 -0.99127426 -0.99993942 -0.98813245 -0.95609507 -0.90448319
 -0.83435349 -0.74714176 -0.64463351 -0.52892744 -0.40239244 -0.26761911
 -0.12736671  0.01549332  0.15803614  0.29734344  0.4305631   0.55496769
  0.66801022  0.76737632  0.85103163  0.91726346  0.96471581  0.99241717
  0.99980039  0.98671433  0.9534269   0.90061959  0.82937357  0.74114747]
sines > 0.5:
 [ True  True  True  True  True  True  True  True  True  True  True  True
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False  True  True  True  True  True  True  True
  True  True  True  True  True

In [362]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

#My example 39


In [363]:
print(senos)
senos[[0, 3, 9]]

[ 0.84147098  0.90996827  0.95983544  0.99005153  0.99999793  0.989471
  0.95868625  0.90827395  0.83926623  0.75307589  0.65146754  0.53652146
  0.41059097  0.27625429  0.13626176 -0.00652051 -0.14916928 -0.28876406
 -0.42244686 -0.54748074 -0.66130585 -0.76159179 -0.84628538 -0.91365265
 -0.96231437 -0.99127426 -0.99993942 -0.98813245 -0.95609507 -0.90448319
 -0.83435349 -0.74714176 -0.64463351 -0.52892744 -0.40239244 -0.26761911
 -0.12736671  0.01549332  0.15803614  0.29734344  0.4305631   0.55496769
  0.66801022  0.76737632  0.85103163  0.91726346  0.96471581  0.99241717
  0.99980039  0.98671433  0.9534269   0.90061959  0.82937357  0.74114747]


array([0.84147098, 0.99005153, 0.75307589])

In [364]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

#My example 40


In [365]:
unsorted_dato = np.array([619, 6197, 619, 7684, -798, 551, -224])

In [366]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

#My example 41


In [367]:
sort_indice = np.argsort(unsorted_dato)
sort_indice

array([4, 6, 5, 0, 2, 1, 3])

In [368]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

#My example 42


In [369]:
unsorted_dato[sort_indice]

array([-798, -224,  551,  619,  619, 6197, 7684])

In [370]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

#My example 43


In [371]:
market_capos = np.array([1122, 641, 1150, 523,116]) 
assets = np.array(['O', 'D', 'S', 'D', 'K'])

In [372]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'D', 'K', 'S', 'O'], dtype='<U1')

#My example 44


In [373]:
sort_by_mcapo = np.argsort(market_capos)
assets[sort_by_mcapo]


array(['K', 'D', 'D', 'O', 'S'], dtype='<U1')

On multi-dimensional arrays, we can slice along each axis independently.

In [374]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#My example 45


In [375]:
dato = np.arange(16).reshape(4, 4)
dato

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [376]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

#My example 46


In [377]:
dato[:2, :2]

array([[0, 1],
       [4, 5]])

In [378]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

#My example 47


In [379]:
dato[:2, [0, -1]]

array([[0, 3],
       [4, 7]])

In [380]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

#My example 48


In [381]:
dato[(dato[:, 3] % 5) == 0]

array([[12, 13, 14, 15]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [382]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

#My example 49


In [383]:
variance(np.random.standard_normal(2500))

1.0660221963907053

In [384]:
variance(np.random.standard_normal(1000))

1.0623992460736253

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [385]:
data = np.arange(30)
data.mean()

14.5

#My example 50


In [386]:
dato = np.arange(280)
dato.mean()

139.5

- ...but we can do more interesting things with multi-dimensional arrays.

#My example 51


In [387]:
dato = np.arange(60).reshape(4, 15)
dato

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [388]:
data.mean()

14.5

#My example 52


In [389]:
dato.mean()


29.5

In [390]:
data.mean(axis=0)

14.5

#My example 53


In [391]:
dato.mean(axis=0)

array([22.5, 23.5, 24.5, 25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5,
       33.5, 34.5, 35.5, 36.5])

#My example 54


In [394]:
dato.mean(axis=1)

array([ 7., 22., 37., 52.])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [395]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


#My example 55


In [396]:
fila = np.array([8, 349, 82353, 54])
columna = np.array([[715], [619], [316]])
print("fila:\n", fila, sep='')
print("columna:\n", columna, sep='')

fila:
[    8   349 82353    54]
columna:
[[715]
 [619]
 [316]]


In [397]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

#My example 56


In [398]:
fila + columna

array([[  723,  1064, 83068,   769],
       [  627,   968, 82972,   673],
       [  324,   665, 82669,   370]])

<center><img src="images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [399]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Mean:
14.5
Data - Mean:
[-14.5 -13.5 -12.5 -11.5 -10.5  -9.5  -8.5  -7.5  -6.5  -5.5  -4.5  -3.5
  -2.5  -1.5  -0.5   0.5   1.5   2.5   3.5   4.5   5.5   6.5   7.5   8.5
   9.5  10.5  11.5  12.5  13.5  14.5]


#My example 57


In [400]:
print("Data:\n", dato, sep='')
print("Mean:\n", dato.mean(axis=0), sep='')
print("Data - Mean:\n", dato - dato.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]]
Mean:
[22.5 23.5 24.5 25.5 26.5 27.5 28.5 29.5 30.5 31.5 32.5 33.5 34.5 35.5
 36.5]
Data - Mean:
[[-22.5 -22.5 -22.5 -22.5 -22.5 -22.5 -22.5 -22.5 -22.5 -22.5 -22.5 -22.5
  -22.5 -22.5 -22.5]
 [ -7.5  -7.5  -7.5  -7.5  -7.5  -7.5  -7.5  -7.5  -7.5  -7.5  -7.5  -7.5
   -7.5  -7.5  -7.5]
 [  7.5   7.5   7.5   7.5   7.5   7.5   7.5   7.5   7.5   7.5   7.5   7.5
    7.5   7.5   7.5]
 [ 22.5  22.5  22.5  22.5  22.5  22.5  22.5  22.5  22.5  22.5  22.5  22.5
   22.5  22.5  22.5]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [401]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

#My example 58


In [402]:
Y = pd.Series(index=['O', 'D', 'S', 'N', 'M'], data=[121, 4232, 64, 2154, 715])
Y 

O     121
D    4232
S      64
N    2154
M     715
dtype: int64

In [403]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


#My example 59


In [404]:
print("The index is:", Y.index)
print("The values are:", Y.values)

The index is: Index(['O', 'D', 'S', 'N', 'M'], dtype='object')
The values are: [ 121 4232   64 2154  715]


In [405]:
# We can look up values out of a Series by position...
s.iloc[0]

1

#My example 60


In [406]:
Y.iloc[0]

121

In [407]:
# ... or by label.
s.loc['a']

1

#My example 61


In [408]:
Y.loc['D']

4232

In [409]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

#My example 62


In [410]:
Y.iloc[:2]

O     121
D    4232
dtype: int64

In [411]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

#My example 63


In [412]:
Y.loc[:'O']

O    121
dtype: int64

In [413]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

#My example 64


In [414]:
Y.iloc[[0, -1]]

O    121
M    715
dtype: int64

In [415]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

#My example 65


In [416]:
Y.loc[Y > 144]

D    4232
N    2154
M     715
dtype: int64

In [417]:
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

#My example 66


In [418]:
other_y = pd.Series({'O': 619, 'D': 2001.0, 'S': 170, 'Z': 20})
other_y

O     619.0
D    2001.0
S     170.0
Z      20.0
dtype: float64

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# FIN DEL COMUNICADO